In [1]:
import cv2 as cv
print(cv.__version__)

4.5.1


### numpy array indexing

In [2]:
img_test = cv.imread('test.jpg')
print(type(img_test))
print(img_test.shape)
print(img_test[90:,90:,0]) 

print()

img_cvtGray = cv.cvtColor(img_test, cv.COLOR_BGR2GRAY)
print(img_cvtGray[90:,90:])
print(img_cvtGray.shape)

<class 'numpy.ndarray'>
(323, 430, 3)
[[147 167 214 ... 237 237 237]
 [169 219 226 ... 237 237 237]
 [216 225 222 ... 238 238 238]
 ...
 [240 240 240 ... 239 239 239]
 [240 240 240 ... 239 239 239]
 [240 240 240 ... 239 239 239]]

[[158 174 218 ... 237 237 237]
 [176 223 228 ... 237 237 237]
 [220 227 224 ... 238 238 238]
 ...
 [240 240 240 ... 239 239 239]
 [240 240 240 ... 239 239 239]
 [240 240 240 ... 239 239 239]]
(323, 430)


### 얕은 복사(같은 id) vs 깊은 복사(다른 id)

In [3]:
# 1. 얕은 복사
a = [1,2,3]
b = a
print(id(a), id(b)) # 같은 id (같은 주소값)

b[0] = 5000
print(a, b) # 같은 곳을 가리키므로, b를 바꿔도 a값까지 바뀜!

print()

# 2. 깊은 복사
c = [1,2,3]
d = c.copy()
print(id(c), id(d))

d[0] = 5000
print(c, d)

2741612483968 2741612483968
[5000, 2, 3] [5000, 2, 3]

2741612482816 2741612484544
[1, 2, 3] [5000, 2, 3]


### 함수로 배열 넘기기
함수로 배열을 넘기는 행위가 배열 자체를 전달해서 새로운 배열로 복사하는 것이 아니라, **"주소값"**을 넘겨주는 것이다!

In [4]:
import numpy as np

def test(arr):
    print(id(arr))

arr_test = np.ones(10)
print(id(arr_test))
test(arr_test)    

2741633105392
2741633105392


### cv2.equalizeHist(ds.pixel_array)
The function equalizeHist is histogram equalization of images and only implemented for CV_8UC1 type, which is a single channel 8 bit unsigned integral type.  
> 따라서 원본이 1000 넘는 값들로 이루어져 uint8 (8bit, 256)이 아니므로, 이 opencv함수 말고 직접 코딩해야됨...  
>  ==> **map_uint16_to_uint8() 함수!**

### cf. fail modules
* ArrayDicom = np.zeros(shape, dtype=np.uint8)
* cv.equalizeHist()
* cv.createCLAHE()
* cv.normalize()
* skimage.util.img_as_ubyte() (from skimage import ima_as_ubyte) 

<hr>

In [5]:
import cv2 as cv
import glob
import pydicom as dicom
import os
import numpy as np

# array indexing using np.where
def Overlay(back, front, rows, cols):
    back[:, :, 0] = np.where(front != 0, back[:, :, 0] * 0.7 + 255 * 0, 0)
    back[:, :, 1] = np.where(front != 0, back[:, :, 1] * 0.7 + 255 * 0, 0)
    back[:, :, 2] = np.where(front != 0, back[:, :, 2] * 0.7 + 255 * 0.3, 0)
    
    #print(back.shape) # (512, 512, 3) ==> (열, 행, 면)
    
    '''
    for i in range(rows):
        for j in range(cols):
            if (front[i][j] == 0) : continue
            
            # linear interpolation
            back[i][j][0] = back[i][j][0] * 0.7 + 255 * 0 # b
            back[i][j][1] = back[i][j][1] * 0.7 + 255 * 0 # g
            back[i][j][2] = back[i][j][2] * 0.7 + 255 * 0.3 # r
    '''

# from 0 ~ 4095 (16bit, uint16) to 0 ~ 255 (8bit, uint8)
def map_uint16_to_uint8(img, lower_bound=None, upper_bound=None):
    lower_bound = np.min(img)
    upper_bound = np.max(img)
    
    if not(0 <= lower_bound < 2**16) and lower_bound is not None:
        raise ValueError(
            '"lower_bound" must be in the range [0, 65535]')
    if not(0 <= upper_bound < 2**16) and upper_bound is not None:
        raise ValueError(
            '"upper_bound" must be in the range [0, 65535]')
    if lower_bound is None:
        lower_bound = np.min(img)
    if upper_bound is None:
        upper_bound = np.max(img)
    if lower_bound >= upper_bound:
        raise ValueError(
            '"lower_bound" must be smaller than "upper_bound"')
    lut = np.concatenate([
        np.zeros(lower_bound, dtype=np.uint16),
        np.linspace(0, 255, upper_bound - lower_bound).astype(np.uint16),
        np.ones(2**16 - upper_bound, dtype=np.uint16) * 255
    ])
    return lut[img].astype(np.uint8)



def main():
    files_str = [file for file in glob.glob("C:/Users/Administrator/Desktop/jiwon/dilab/Projects/180509_SampleData_CT/*.dcm")] # imrepyad(dcm) : None
    
    for f in files_str:
        print(f)
        ori = dicom.read_file(f) # get dicom file / type : <class 'pydicom.dataset.FileDataset'> / size : (512, 512)       
        rows, cols = ori.Rows, ori.Columns
        
        ori1 = map_uint16_to_uint8(ori.pixel_array) # type : np.ndarray ==> cv.imread img도 np.ndarray형!
        img_copy = ori1.copy()
        
        
        # 1. Bilateral Filtering (noise filtering)
        filtered = cv.bilateralFilter(img_copy, -1, 15, 15)
        
        
        # 2. Otsu;s Thresholding (cv2.threshold(src, 0(**T not defined**), 255(change to 255), flag(binary & otsu)))
        ret,otsu = cv.threshold(filtered, 0, 255, cv.THRESH_BINARY + cv.THRESH_OTSU) # 히스토그램 분석 후 자동으로 T값(ret) 구해서 적용
        
        
        # 3. Morphology_preprocessing(remove outlines with erode) ==> anchor(point) default : (-1, -1)
        mask = cv.getStructuringElement(cv.MORPH_RECT,(3,3))
        pre_erode = cv.erode(otsu, mask, iterations = 7)
        pre_dilate = cv.dilate(pre_erode, mask, iterations = 7)
        
        
        # 4. Floodfill (combine background to select hole in body) ==> mask : None (not used)
        hole = pre_dilate.copy()
        cv.floodFill(hole, None, (0, 0), 255)
        cv.floodFill(hole, None, (cols-1, rows-1), 255)
    
    
        # 5. Invert hole
        hole_inv = cv.bitwise_not(hole) # == np.bitwise_not == np.invert
        
        
        # 6. bitwise OR (combine pre(bone) and hole)
        bitor = np.bitwise_or(pre_dilate, hole_inv)
        
        
        # 7. overlay
        back3C = cv.cvtColor(ori1, cv.COLOR_GRAY2BGR) # 3channel
        front = bitor.copy()
        Overlay(back3C, front, rows, cols)
        
        
        result_path = "C:/Users/Administrator/Desktop/jiwon/dilab/Projects/180509_SampleData_CT/result_python/"
        cv.imwrite(result_path + f[-10:-4] + '.png', back3C) # f : "~/CT0002.dcm"
        
    
    
main()

C:/Users/Administrator/Desktop/jiwon/dilab/Projects/180509_SampleData_CT\CT0002.dcm
C:/Users/Administrator/Desktop/jiwon/dilab/Projects/180509_SampleData_CT\CT0003.dcm
C:/Users/Administrator/Desktop/jiwon/dilab/Projects/180509_SampleData_CT\CT0004.dcm
C:/Users/Administrator/Desktop/jiwon/dilab/Projects/180509_SampleData_CT\CT0005.dcm
C:/Users/Administrator/Desktop/jiwon/dilab/Projects/180509_SampleData_CT\CT0006.dcm
C:/Users/Administrator/Desktop/jiwon/dilab/Projects/180509_SampleData_CT\CT0007.dcm
C:/Users/Administrator/Desktop/jiwon/dilab/Projects/180509_SampleData_CT\CT0008.dcm
C:/Users/Administrator/Desktop/jiwon/dilab/Projects/180509_SampleData_CT\CT0009.dcm
C:/Users/Administrator/Desktop/jiwon/dilab/Projects/180509_SampleData_CT\CT0010.dcm
C:/Users/Administrator/Desktop/jiwon/dilab/Projects/180509_SampleData_CT\CT0011.dcm
C:/Users/Administrator/Desktop/jiwon/dilab/Projects/180509_SampleData_CT\CT0012.dcm
C:/Users/Administrator/Desktop/jiwon/dilab/Projects/180509_SampleData_CT\CT0

C:/Users/Administrator/Desktop/jiwon/dilab/Projects/180509_SampleData_CT\CT0101.dcm
C:/Users/Administrator/Desktop/jiwon/dilab/Projects/180509_SampleData_CT\CT0102.dcm
C:/Users/Administrator/Desktop/jiwon/dilab/Projects/180509_SampleData_CT\CT0103.dcm
C:/Users/Administrator/Desktop/jiwon/dilab/Projects/180509_SampleData_CT\CT0104.dcm
C:/Users/Administrator/Desktop/jiwon/dilab/Projects/180509_SampleData_CT\CT0105.dcm
C:/Users/Administrator/Desktop/jiwon/dilab/Projects/180509_SampleData_CT\CT0106.dcm
C:/Users/Administrator/Desktop/jiwon/dilab/Projects/180509_SampleData_CT\CT0107.dcm
C:/Users/Administrator/Desktop/jiwon/dilab/Projects/180509_SampleData_CT\CT0108.dcm
C:/Users/Administrator/Desktop/jiwon/dilab/Projects/180509_SampleData_CT\CT0109.dcm
C:/Users/Administrator/Desktop/jiwon/dilab/Projects/180509_SampleData_CT\CT0110.dcm
C:/Users/Administrator/Desktop/jiwon/dilab/Projects/180509_SampleData_CT\CT0111.dcm
C:/Users/Administrator/Desktop/jiwon/dilab/Projects/180509_SampleData_CT\CT0

<hr>

## [PyQt]

### select file

In [1]:
import sys
from PyQt5.QtWidgets import *

In [2]:
# prevent kernel from dying
from PyQt5.QtWidgets import QApplication, QDialog
from PyQt5.QtCore import QCoreApplication

In [3]:
class MyWindow(QWidget):
    def __init__(self):
        super().__init__()
        self.setupUI()

    def setupUI(self):
        self.setGeometry(800, 200, 300, 300)
        self.setWindowTitle("Get Files")

        self.pushButton = QPushButton("Select Folder")
        self.pushButton.clicked.connect(self.pushButtonClicked)
        self.label = QLabel()

        layout = QVBoxLayout()
        layout.addWidget(self.pushButton)
        layout.addWidget(self.label)

        self.setLayout(layout)

    def pushButtonClicked(self):
        '''
        fname = QFileDialog.getOpenFileName(self) # 해당 파일의 절대 경로 반환 (tuple)
        self.label.setText(fname[0]) # tuple의 0번째 값(경로) 창에 출력
        print(fname)
        '''
        options = QFileDialog.Options()
        options |= QFileDialog.ShowDirsOnly
        working_path = QFileDialog.getExistingDirectory(self, "select Directory")
        return working_path

def getPath():
    # prevent kernel from dying
    app = QCoreApplication.instance()
    if app is None:
        app = QApplication(sys.argv)
        
    window = MyWindow()
    window.show()
    src_path = window.pushButtonClicked()
    #app.exec_() => ?
    return src_path

### drag and drop

In [11]:
from PyQt5.QtWidgets import QMainWindow, QApplication
import sys


class MainWidget(QMainWindow):
    def __init__(self):
        super().__init__()
        self.setWindowTitle("Drag and Drop")
        self.resize(720, 480)
        self.setAcceptDrops(True)

    def dragEnterEvent(self, event):
        if event.mimeData().hasUrls():
            event.accept()
        else:
            event.ignore()

    def dropEvent(self, event):
        files = [u.toLocalFile() for u in event.mimeData().urls()]
        
        for f in files:
            print(f)
        


def dragAndDrop():
    app = QApplication(sys.argv)
    ui = MainWidget()
    ui.show()
    sys.exit(app.exec_())

In [14]:
print('hi')

hi


In [12]:
dragAndDrop()

D:/_jiwon_/datasets/190906_Patient10b_CT
D:/_jiwon_/datasets/191004_Patient11_CT
D:/_jiwon_/datasets/191024_Demo_CT
D:/_jiwon_/datasets/191220_Patient12_CT
D:/_jiwon_/datasets/200206_Patient13_CT
D:/_jiwon_/datasets/200218_Patient14_CT
D:/_jiwon_/datasets/200225_Patient15_CT
D:/_jiwon_/datasets/180509_SampleData_CT
D:/_jiwon_/datasets/190208_Patient2a_CT
D:/_jiwon_/datasets/190212_Patient3b_CT
D:/_jiwon_/datasets/190320_Patient4_CT
D:/_jiwon_/datasets/190426_Patient6a(7)_CT
D:/_jiwon_/datasets/190426_Patient6b(6)_CT
D:/_jiwon_/datasets/190509_Patient8_CT
D:/_jiwon_/datasets/190531_Patient9_CT
D:/_jiwon_/datasets/190906_Patient10a_CT


SystemExit: 0

### apply to CTSS

In [4]:
import cv2 as cv
import glob
import pydicom as dicom
import os
import numpy as np

# array indexing using np.where
def Overlay(back, front, rows, cols):
    back[:, :, 0] = np.where(front != 0, back[:, :, 0] * 0.7 + 255 * 0, 0)
    back[:, :, 1] = np.where(front != 0, back[:, :, 1] * 0.7 + 255 * 0, 0)
    back[:, :, 2] = np.where(front != 0, back[:, :, 2] * 0.7 + 255 * 0.3, 0)
    
    #print(back.shape) # (512, 512, 3) ==> (열, 행, 면)
    
    '''
    for i in range(rows):
        for j in range(cols):
            if (front[i][j] == 0) : continue
            
            # linear interpolation
            back[i][j][0] = back[i][j][0] * 0.7 + 255 * 0 # b
            back[i][j][1] = back[i][j][1] * 0.7 + 255 * 0 # g
            back[i][j][2] = back[i][j][2] * 0.7 + 255 * 0.3 # r
    '''

# from 0 ~ 4095 (16bit, uint16) to 0 ~ 255 (8bit, uint8)
def map_uint16_to_uint8(img, lower_bound=None, upper_bound=None):
    lower_bound = np.min(img)
    upper_bound = np.max(img)
    
    if not(0 <= lower_bound < 2**16) and lower_bound is not None:
        raise ValueError(
            '"lower_bound" must be in the range [0, 65535]')
    if not(0 <= upper_bound < 2**16) and upper_bound is not None:
        raise ValueError(
            '"upper_bound" must be in the range [0, 65535]')
    if lower_bound is None:
        lower_bound = np.min(img)
    if upper_bound is None:
        upper_bound = np.max(img)
    if lower_bound >= upper_bound:
        raise ValueError(
            '"lower_bound" must be smaller than "upper_bound"')
    lut = np.concatenate([
        np.zeros(lower_bound, dtype=np.uint16),
        np.linspace(0, 255, upper_bound - lower_bound).astype(np.uint16),
        np.ones(2**16 - upper_bound, dtype=np.uint16) * 255
    ])
    return lut[img].astype(np.uint8)



def main():
    src_path = getPath()
    print('src dir path :', src_path)
    files_str = [file for file in glob.glob(src_path+"/*.dcm")] # imrepyad(dcm) : None
    
    for f in files_str:
        print(f)
        ori = dicom.read_file(f) # get dicom file / type : <class 'pydicom.dataset.FileDataset'> / size : (512, 512)       
        rows, cols = ori.Rows, ori.Columns
        
        ori1 = map_uint16_to_uint8(ori.pixel_array) # type : np.ndarray ==> cv.imread img도 np.ndarray형!
        img_copy = ori1.copy()
        
        
        # 1. Bilateral Filtering (noise filtering)
        filtered = cv.bilateralFilter(img_copy, -1, 15, 15)
        
        
        # 2. Otsu;s Thresholding (cv2.threshold(src, 0(**T not defined**), 255(change to 255), flag(binary & otsu)))
        ret,otsu = cv.threshold(filtered, 0, 255, cv.THRESH_BINARY + cv.THRESH_OTSU) # 히스토그램 분석 후 자동으로 T값(ret) 구해서 적용
        
        
        # 3. Morphology_preprocessing(remove outlines with erode) ==> anchor(point) default : (-1, -1)
        mask = cv.getStructuringElement(cv.MORPH_RECT,(3,3))
        pre_erode = cv.erode(otsu, mask, iterations = 7)
        pre_dilate = cv.dilate(pre_erode, mask, iterations = 7)
        
        
        # 4. Floodfill (combine background to select hole in body) ==> mask : None (not used)
        hole = pre_dilate.copy()
        cv.floodFill(hole, None, (0, 0), 255)
        cv.floodFill(hole, None, (cols-1, rows-1), 255)
    
    
        # 5. Invert hole
        hole_inv = cv.bitwise_not(hole) # == np.bitwise_not == np.invert
        
        
        # 6. bitwise OR (combine pre(bone) and hole)
        bitor = np.bitwise_or(pre_dilate, hole_inv)
        
        
        # 7. overlay
        back3C = cv.cvtColor(ori1, cv.COLOR_GRAY2BGR) # 3channel
        front = bitor.copy()
        Overlay(back3C, front, rows, cols)
        
        # src_path : D:/_jiwon_/datasets/180509_SampleData_CT
        result_path = src_path + '/result/'
        cv.imwrite(result_path + f[-10:-4] + '.png', back3C) # f : "~/CT0002.dcm" => **슬라이싱 수정하기!**
        
    
    
main()

src dir path : D:/_jiwon_/datasets/180509_SampleData_CT
D:/_jiwon_/datasets/180509_SampleData_CT\CT0002.dcm
D:/_jiwon_/datasets/180509_SampleData_CT\CT0003.dcm
D:/_jiwon_/datasets/180509_SampleData_CT\CT0004.dcm
D:/_jiwon_/datasets/180509_SampleData_CT\CT0005.dcm
D:/_jiwon_/datasets/180509_SampleData_CT\CT0006.dcm
D:/_jiwon_/datasets/180509_SampleData_CT\CT0007.dcm
D:/_jiwon_/datasets/180509_SampleData_CT\CT0008.dcm
D:/_jiwon_/datasets/180509_SampleData_CT\CT0009.dcm
D:/_jiwon_/datasets/180509_SampleData_CT\CT0010.dcm
D:/_jiwon_/datasets/180509_SampleData_CT\CT0011.dcm
D:/_jiwon_/datasets/180509_SampleData_CT\CT0012.dcm
D:/_jiwon_/datasets/180509_SampleData_CT\CT0013.dcm
D:/_jiwon_/datasets/180509_SampleData_CT\CT0014.dcm
D:/_jiwon_/datasets/180509_SampleData_CT\CT0015.dcm
D:/_jiwon_/datasets/180509_SampleData_CT\CT0016.dcm
D:/_jiwon_/datasets/180509_SampleData_CT\CT0017.dcm
D:/_jiwon_/datasets/180509_SampleData_CT\CT0018.dcm
D:/_jiwon_/datasets/180509_SampleData_CT\CT0019.dcm
D:/_jiwo

D:/_jiwon_/datasets/180509_SampleData_CT\CT0159.dcm
D:/_jiwon_/datasets/180509_SampleData_CT\CT0160.dcm
D:/_jiwon_/datasets/180509_SampleData_CT\CT0161.dcm
D:/_jiwon_/datasets/180509_SampleData_CT\CT0162.dcm
D:/_jiwon_/datasets/180509_SampleData_CT\CT0163.dcm
D:/_jiwon_/datasets/180509_SampleData_CT\CT0164.dcm
D:/_jiwon_/datasets/180509_SampleData_CT\CT0165.dcm
D:/_jiwon_/datasets/180509_SampleData_CT\CT0166.dcm
D:/_jiwon_/datasets/180509_SampleData_CT\CT0167.dcm
D:/_jiwon_/datasets/180509_SampleData_CT\CT0168.dcm
D:/_jiwon_/datasets/180509_SampleData_CT\CT0169.dcm
D:/_jiwon_/datasets/180509_SampleData_CT\CT0170.dcm
D:/_jiwon_/datasets/180509_SampleData_CT\CT0171.dcm
D:/_jiwon_/datasets/180509_SampleData_CT\CT0172.dcm
D:/_jiwon_/datasets/180509_SampleData_CT\CT0173.dcm
D:/_jiwon_/datasets/180509_SampleData_CT\CT0174.dcm
D:/_jiwon_/datasets/180509_SampleData_CT\CT0175.dcm
D:/_jiwon_/datasets/180509_SampleData_CT\CT0176.dcm
D:/_jiwon_/datasets/180509_SampleData_CT\CT0177.dcm
D:/_jiwon_/d